import { readFile, writeFile } from "node:fs/promises";
const [sourcePath, outputPath] = process.argv.slice(2);
if (!sourcePath || !outputPath) {
  throw new Error("Usage: node scripts/generate-theme.mjs <tokens.json> <output.css>");
}

const tokens = JSON.parse(await readFile(sourcePath, "utf8"));
if (tokens.schemaVersion !== 1 || tokens.brand !== "axiowl") {
  throw new Error("Unsupported AxiOwl theme token schema");
}

const cssName = (name) => `--axiowl-${name.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`)}`;
const lines = [
  "/* Generated by scripts/generate-theme.mjs. Do not edit this file directly. */",
  ":root {",
];

for (const [name, value] of Object.entries(tokens.common.spacing)) {
  lines.push(`  --axiowl-spacing-${name.replace('.', '-')}: ${value}px;`);
}
for (const [name, value] of Object.entries(tokens.common.fontSize)) {
  lines.push(`  --axiowl-font-size-${name.replace('.', '-')}: ${value}px;`);
}
for (const [name, value] of Object.entries(tokens.common.borderRadius)) {
  lines.push(`  --axiowl-radius-${name}: ${value}px;`);
}
lines.push(`  --axiowl-font-family-ui: ${tokens.common.fontFamily.ui};`);
lines.push(`  --axiowl-font-family-mono: ${tokens.common.fontFamily.mono};`);
lines.push("}");

for (const [scheme, values] of Object.entries({ light: tokens.light, dark: tokens.dark })) {
  lines.push(`${scheme === "light" ? ":root" : "[data-theme='dark']"} {`);
  for (const [name, value] of Object.entries(values)) {
    if (name === "shadow") continue;
    lines.push(`  ${cssName(name)}: ${value};`);
  }
  for (const [name, value] of Object.entries(values.shadow)) {
    lines.push(`  --axiowl-shadow-${name}: ${value};`);
  }
  lines.push("}");
}

await writeFile(outputPath, `${lines.join("\n")}\n`, "utf8");
